OPEN_API_KEY = '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'
OPEN_API_KEY2 = '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'
GROQ_API_KEY = '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'